In [1]:
import numpy as np
import pandas as pd

### 1. Series and Index

In [8]:
s1 = pd.Series(range(0, 4))
s2 = pd.Series(range(1, 5))
print(s1)
print(s2)
s3 = s1 + s2
print(s3)
s4 = pd.Series(['a', 'b']) * 3
print(s4)

0    0
1    1
2    2
3    3
dtype: int64
0    1
1    2
2    3
3    4
dtype: int64
0    1
1    3
2    5
3    7
dtype: int64
0    aaa
1    bbb
dtype: object


In [12]:
idx = s1.index
a = idx.values  # get a numpy array
print(a, type(a), sep='\t')
l = idx.tolist();
print(l, type(l), sep='\t') # get a python list

[0 1 2 3]	<class 'numpy.ndarray'>
[0, 1, 2, 3]	<class 'list'>


In [24]:
idx = pd.Index([1, 3]);
print(s2)
print(s2[idx])
print(idx.min(), idx.max())
array = [1, 2, 3, 4, 5]


0    1
1    2
2    3
3    4
dtype: int64
1    2
3    4
dtype: int64
1 3
5


### 2. DateFrame

In [33]:
twoDemArr = np.random.randint(0, 100, [10, 4])
df = pd.DataFrame(twoDemArr, columns=['A', 'B', 'C', 'D'], index=range(100, 110))
df

A   B   C   D
100  91  63  64  67
101  84  45  88  24
102  63  18  14  48
103  81  57  14  19
104  61  72  47  99
105   1  59  19   3
106  55  37  31  26
107  67  38  24   0
108  24  44  48  87
109  39  36   3  61

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 100 to 109
Data columns (total 4 columns):
A    10 non-null int64
B    10 non-null int64
C    10 non-null int64
D    10 non-null int64
dtypes: int64(4)
memory usage: 404.0 bytes


In [35]:
df.head() # by default the row No. is 5

A   B   C   D
100  91  63  64  67
101  84  45  88  24
102  63  18  14  48
103  81  57  14  19
104  61  72  47  99

In [36]:
df.tail(3)

A   B   C   D
107  67  38  24   0
108  24  44  48  87
109  39  36   3  61

In [37]:
df.describe()

A         B          C          D
count  10.00000  10.00000  10.000000  10.000000
mean   56.60000  46.90000  35.200000  43.400000
std    28.21426  15.91959  26.376757  34.432543
min     1.00000  18.00000   3.000000   0.000000
25%    43.00000  37.25000  15.250000  20.250000
50%    62.00000  44.50000  27.500000  37.000000
75%    77.50000  58.50000  47.750000  65.500000
max    91.00000  72.00000  88.000000  99.000000

In [38]:
df.T # reverse the Table

100  101  102  103  104  105  106  107  108  109
A   91   84   63   81   61    1   55   67   24   39
B   63   45   18   57   72   59   37   38   44   36
C   64   88   14   14   47   19   31   24   48    3
D   67   24   48   19   99    3   26    0   87   61

In [39]:
df.shape # the shape of table (row, column)

(10, 4)

In [40]:
df.T.shape

(4, 10)

In [42]:
df.size # total numbers of table

40

In [44]:
print(type(df), type(df.values), df.values)

<class 'pandas.core.frame.DataFrame'> <class 'numpy.ndarray'> [[91 63 64 67]
 [84 45 88 24]
 [63 18 14 48]
 [81 57 14 19]
 [61 72 47 99]
 [ 1 59 19  3]
 [55 37 31 26]
 [67 38 24  0]
 [24 44 48 87]
 [39 36  3 61]]


### 3. DataFrame Column Processing

In [45]:
df.columns # Index Type

Index(['A', 'B', 'C', 'D'], dtype='object')

In [46]:
df.rename(columns={'A': 1, 'B': 2})

1   2   C   D
100  91  63  64  67
101  84  45  88  24
102  63  18  14  48
103  81  57  14  19
104  61  72  47  99
105   1  59  19   3
106  55  37  31  26
107  67  38  24   0
108  24  44  48  87
109  39  36   3  61

In [47]:
df['C'] # Get Serise Type

100    64
101    88
102    14
103    14
104    47
105    19
106    31
107    24
108    48
109     3
Name: C, dtype: int64

In [48]:
df[['C']] # Get DataFrame

C
100  64
101  88
102  14
103  14
104  47
105  19
106  31
107  24
108  48
109   3

In [49]:
df[['C', 'B']]

C   B
100  64  63
101  88  45
102  14  18
103  14  57
104  47  72
105  19  59
106  31  37
107  24  38
108  48  44
109   3  36

In [54]:
df[df.columns[[1, 2]]]

B   C
100  63  64
101  45  88
102  18  14
103  57  14
104  72  47
105  59  19
106  37  31
107  38  24
108  44  48
109  36   3

In [59]:
df.B

100    63
101    45
102    18
103    57
104    72
105    59
106    37
107    38
108    44
109    36
Name: B, dtype: int64

In [62]:
df['new_col'] = range(len(df))
df.head()

A   B   C   D  new_col
100  91  63  64  67        0
101  84  45  88  24        1
102  63  18  14  48        2
103  81  57  14  19        3
104  61  72  47  99        4

### 4. DataFrame Row Processing

In [64]:
df.index

RangeIndex(start=100, stop=110, step=1)

In [67]:
df1 = df.rename(index={100: 'B', 101: 20.5}) # rename index name
df1

A   B   C   D  new_col
B     91  63  64  67        0
20.5  84  45  88  24        1
102   63  18  14  48        2
103   81  57  14  19        3
104   61  72  47  99        4
105    1  59  19   3        5
106   55  37  31  26        6
107   67  38  24   0        7
108   24  44  48  87        8
109   39  36   3  61        9

In [71]:
df.drop([100, 101]) # delete rows

A   B   C   D  new_col
102  63  18  14  48        2
103  81  57  14  19        3
104  61  72  47  99        4
105   1  59  19   3        5
106  55  37  31  26        6
107  67  38  24   0        7
108  24  44  48  87        8
109  39  36   3  61        9

### 5. Index and Slicing
    There are 3 ways: loc, iloc, ix
    loc严格通过标签索引
    iloc严格通过行号和列号索引
    ix则结合两种

In [72]:
df.loc[102:107, 'B':'C']

B   C
102  18  14
103  57  14
104  72  47
105  59  19
106  37  31
107  38  24

In [75]:
df.iloc[0:3, 1:3]

B   C
100  63  64
101  45  88
102  18  14

In [76]:
df['B'] # Get Column

100    63
101    45
102    18
103    57
104    72
105    59
106    37
107    38
108    44
109    36
Name: B, dtype: int64

In [78]:
df[0:1] # Get Row by using slice opration

A   B   C   D  new_col
100  91  63  64  67        0